CREATE DATABASE PACIFIER;
GO

USE PACIFIER;
GO

CREATE TABLE USUARIO (
CPF_USU INT NOT NULL,
NOME_USU VARCHAR(35) NOT NULL,
NUM_USU INT NOT NULL,
CEP_USU INT NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF_USU));
GO

CREATE TABLE ANUNCIO (
COD_ANUNCIO INT NOT NULL,
NOME_ANUNCIO VARCHAR(60),
DES_ANUNCIO VARCHAR(250),
VALOR_ANUNCIO INT NOT NULL,
CPF_USU INT,
CONSTRAINT PK_ANUNCIO PRIMARY KEY (COD_ANUNCIO),
CONSTRAINT FK_ANUNCIO_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU));
GO

CREATE TABLE CAD_PRODUTO (
COD_CAD_PRODUTO INT NOT NULL,
NOME VARCHAR(60),
QUANT INT NOT NULL,
CPF_USU INT,
CONSTRAINT PK_CAD_PRODUTO PRIMARY KEY (COD_CAD_PRODUTO),
CONSTRAINT FK_CAD_PROD_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU));
GO

CREATE TABLE PEDIDO (
NF_PEDIDO INT NOT NULL,
QUANT_PEDIDO INT NOT NULL,
CPF_USU INT,
CONSTRAINT PK_PEDIDO PRIMARY KEY(NF_PEDIDO),
CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU));
GO

CREATE TABLE TROCA (
COD_TROCA INT NOT NULL,
CPF_USU INT,
CONSTRAINT PK_TROCA PRIMARY KEY(COD_TROCA),
CONSTRAINT FK_TROCA_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU));
GO

CREATE TABLE PRODUTO (
COD_PROD INT NOT NULL,
NOME_PROD VARCHAR(60),
VALOR_PROD INT NOT NULL,
COD_ANUNCIO INT,
COD_CAD_PRODUTO INT,
NF_PEDIDO INT,
COD_TROCA INT,
CONSTRAINT PK_PROD PRIMARY KEY (COD_PROD),
CONSTRAINT FK_PRODUTO_ANUNCIO FOREIGN KEY (COD_ANUNCIO) REFERENCES ANUNCIO(COD_ANUNCIO),
CONSTRAINT FK_PRODUTO_CAD_PRODUTO FOREIGN KEY (COD_CAD_PRODUTO) REFERENCES CAD_PRODUTO(COD_CAD_PRODUTO),
CONSTRAINT FK_PRODUTO_PEDIDO FOREIGN KEY (NF_PEDIDO) REFERENCES PEDIDO(NF_PEDIDO),
CONSTRAINT FK_PRODUTO_TROCA FOREIGN KEY (COD_TROCA) REFERENCES TROCA(COD_TROCA));
GO