CREATE DATABASE PACIFIER_VX;
GO

USE PACIFIER_VX;
GO

CREATE TABLE ENDERECO (
CEP_END INT NOT NULL,
NUM_END INT NOT NULL,
RUA_END VARCHAR(15) NOT NULL,
BAIRRO_END VARCHAR(15) NOT NULL,
CIDADE_END VARCHAR(10) NOT NULL,
ESTADO_END VARCHAR(15) NOT NULL,
PAIS_END VARCHAR(15) NOT NULL,
CONSTRAINT PK_ENDERECO PRIMARY KEY (CEP_END));
GO

CREATE TABLE USUARIO (
CPF_USU INT NOT NULL,
NOME_USU VARCHAR(15) NOT NULL,
SOBRENOME_USU VARCHAR(35) NOT NULL,
EMAIL_USU VARCHAR(50) NOT NULL,
SENHA_USU VARCHAR(10) NOT NULL,
NUM_CEL_USU VARCHAR(15) NULL,
GENERO_USU VARCHAR(10),
CEP_END INT,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF_USU),
CONSTRAINT FK_USUARIO_ENDERECO FOREIGN KEY (CEP_END) REFERENCES ENDERECO(CEP_END));
GO

CREATE TABLE PRODUTO (
COD_PROD INT NOT NULL,
NOME_PROD VARCHAR(60),
VALOR_PROD INT NOT NULL,
COD_ANUNCIO INT,
COD_CAD_PRODUTO INT,
NF_PEDIDO INT,
COD_TROCA INT,
CONSTRAINT PK_PROD PRIMARY KEY (COD_PROD));
GO

CREATE TABLE CAD_PRODUTO (
COD_CAD_PRODUTO INT NOT NULL,
COD_PROD INT,
QUANT INT NOT NULL,
CPF_USU INT,
STATUS VARCHAR(10),
CONSTRAINT PK_CAD_PRODUTO PRIMARY KEY (COD_CAD_PRODUTO),
CONSTRAINT FK_PRODUTO_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU),
CONSTRAINT FK_CAD_PRODUTO_PRODUTO FOREIGN KEY (COD_PROD) REFERENCES PRODUTO(COD_PROD)
);
GO


CREATE TABLE TIPO_ANUNCIO (
COD_TIPO_ANUNCIO INT IDENTITY (1,1),
DESC_TIPO_ANUCIO VARCHAR(20),
CONSTRAINT PK_TIPO_ANUNCIO PRIMARY KEY (COD_TIPO_ANUNCIO) 
);
GO

CREATE TABLE ANUNCIO (
COD_ANUNCIO INT NOT NULL,
NOME_ANUNCIO VARCHAR(60),
DES_ANUNCIO VARCHAR(250),
VALOR_ANUNCIO INT NOT NULL,
QUANT_ANUNCIADA INT,
CPF_USU INT,
COD_CAD_PRODUTO INT,
STATUS VARCHAR(15),
COD_TIPO_ANUNCIO INT,
CONSTRAINT PK_ANUNCIO PRIMARY KEY (COD_ANUNCIO),
CONSTRAINT FK_ANUNCIO_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU),
CONSTRAINT FK_ANUNCIO_CAD_PRODUTO FOREIGN KEY (COD_CAD_PRODUTO) REFERENCES CAD_PRODUTO(COD_CAD_PRODUTO));
GO



CREATE TABLE TROCA (
COD_TROCA INT NOT NULL,
COD_CAD_PRODUTO INT,
COD_ANUNCIO INT,
CPF_USU INT,
CONSTRAINT PK_TROCA PRIMARY KEY(COD_TROCA),
CONSTRAINT FK_TROCA_CAD_PRODUTO FOREIGN KEY (COD_CAD_PRODUTO) REFERENCES CAD_PRODUTO(COD_CAD_PRODUTO),
CONSTRAINT FK_TROCA_COD_ANUNCIO FOREIGN KEY (COD_ANUNCIO) REFERENCES ANUNCIO (COD_ANUNCIO),
CONSTRAINT FK_TROCA_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU));
GO


CREATE TABLE PEDIDO (
NF_PEDIDO INT NOT NULL,
DT_PEDIDO DATETIME NOT NULL,
CPF_USU INT,
CONSTRAINT PK_PEDIDO PRIMARY KEY(NF_PEDIDO),
CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (CPF_USU) REFERENCES USUARIO(CPF_USU));
GO

-- Itens
CREATE TABLE ITEM_PEDIDO (
COD_ITEM_PEDIDO INT NOT NULL IDENTITY  (1,1),
NF_PEDIDO INT NOT NULL,
QUANT_PEDIDO INT NOT NULL,
COD_ANUNCIO INT,
CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY(COD_ITEM_PEDIDO),
CONSTRAINT FK_PEDIDO_ITEM_PEDIDO FOREIGN KEY (NF_PEDIDO) REFERENCES PEDIDO(NF_PEDIDO),
CONSTRAINT FK_PEDIDO_ANUNCIO FOREIGN KEY (COD_ANUNCIO ) REFERENCES ANUNCIO(COD_ANUNCIO));